---
title: "Gouvernance"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Gouvernance}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Gouvernance

Cet effort de développement d'un paquet R pour les données du SNDS est un projet communautaire basé sur le consensus et l'investissement personnel de ses membres. Tout utilisateur ayant un intérêt dans le projet peut rejoindre la communauté, contribuer au projet et à ses orientations futures. Ce document précise comment la participation a lieu, comment trouver / gagner sa place dans le projet, et quels sont les différents rôles et responsabilités. 

Actuellement, le paquet essaye de fonctionner avec deux types de contributeurs : 

## Les contributeurs 

Les contributeurs classiques faisant des issues, des reviews et des propositions de nouvelles fonctionnalités (pull requests). Chaque nouvelle fonctionnalité avant d'être intégré doit être revue par un core contributeur

## Les core contributeurs 

Les core contributors sont particulièrement investis dans le projet. Ils ont des accès larges sur le dépôt. Ce sont eux seulement qui valident l'intégration de nouvelles fonctionnalités (pull requests) et peuvent fermer les issues. 

## Devenir un contributeur 

Tout utilisateur peut être contributeur en faisant [une nouvelle issue](https://github.com/strayMat/sndsTools/issues), [une pull request](https://github.com/strayMat/sndsTools/pulls), ou en effectuant une revue sur une pull request existante. Le [guide de contribution](contribuer.html) détaille les différentes manières de contribuer. 

## Devenir un core contributeur 

Après une ou deux pull requests ou reviews de la part d'un nouveau contributeur, sur demande de ce dernier, les core contributeurs décident collégialement de l'intégrer au projet. Le nombre de core contributeur n'est pas limité. Le projet est en phase très précoce, et accueille à bras ouverts de nouveaux core contributeurs 🤗. 
